implemented scripts
kuleshovaann/Delivery-service pull request #3
Opened 2021-04-23 12:49 UTC by kuleshovaann

2021-04-27 11:26 UTC, serhii-shkodenko requested changes

2021-04-27 11:26 UTC, serhii-shkodenko commented on Delivery-service/Models/Order.cs
>      public class Order
Этот класс нарушает Single responsibility principle. Он выполняет слишком много задач. Из его исспользования неясно или это модель для хранения данных, или он осуществляет манипулирование этими данными или выводит их на устройство вывода... Поэтому его нужно переписать.

2021-04-27 11:26 UTC, serhii-shkodenko commented on Delivery-service/Models/Company.cs
>      public class Company : Creator
Этот класс нарушает Single responsibility principle. Он выполняет слишком много задач. Из его исспользования неясно или это модель для хранения данных, или он осуществляет манипулирование этими данными или выводит их на устройство вывода... Поэтому его нужно переписать.

2021-05-04 11:33 UTC, serhii-shkodenko requested changes
У тебя отсутствует слой для работы с бизнес логикой, также нет какого-то хранилища данных. В результате ты вынуждена один объект кидать в методы разных классов, чтобы сохранять там состояние. 

В целом нужно сделать следующее:
1. Объединить классы для работы с пользовательским интерфейсом в один. 
2. Вычленить из них бизнес логику и создать классы для работы с ней. Тогда будет соблюден Single responsibility principle. 
3. Создать хранилище данных. 
4. И для храналища и для сервисов создать интерфейсы, через которые осуществлять связи с зависимостями. В конструкторе класса для работы с пользователем просить параметра с типом интерфейса. Тогда будет соблюден Dependency inversion principle. 

В целом код выглядит чисто. Это очень хорошо.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICustomer.cs
> +    public interface ICustomer
Не создавай пустых интерфейсов. Они не выполняют никаких задач. Удали его, пожалуйста.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Models/Order.cs
> +        public Customer _customer { get; set; }
Это свойство. Его имя должно быть в `PascalCase`.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Models/Order.cs
> +        public List<Dish> Titles;
Это поле. Они используются для инкапсуляции. Судя по тому, что ты его не испльзуешь в рамках этого класса, лучше его переделать на свойство.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICompany.cs
> +        public string Name { get; set; }
Модификатор `public` в интерфейсах избыточен, поэтому его не указывают. Все члены интерфейсов по умолчанию публичные. Его лучше удалить.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/UI/Starter.cs
> +    public class Starter : IStarter
Все классы для работы с пользовательским интерфейсовм лучше объединить в один.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/UI/CustomerUI.cs
> +    class CustomerUI
Все классы для работы с пользовательским интерфейсовм лучше объединить в один.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/UI/CustomerUI.cs
> +    class CustomerUI
Не хватает модификатора доступа.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/UI/CompanyUI.cs
> +    public class CompanyUI
Все классы для работы с пользовательским интерфейсовм лучше объединить в один.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices
Все классы для работы с пользовательским интерфейсовм лучше объединить в один.

2021-05-04 11:33 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CompanyServices.cs
> +    public class CompanyServices
Все классы для работы с пользовательским интерфейсовм лучше объединить в один.

2021-05-12 22:40 UTC, serhii-shkodenko requested changes

2021-05-12 22:40 UTC, serhii-shkodenko commented on Delivery-service/Models/Database/OrderBase.cs
> +        public OrderBase(IOrder order)
Насколько я понимаю, этот класс служит в качестве храналища. Если это так, то его лучше переназвать `OrderDatabase`, поскольку просто `OrderBase` наталкивает на мысль, что это базовый класс для наследования. Кроме того, конструктор не служит цели добавления в хранилище каких либо данных, для этого лучше подойдет класс с бизнес логикой.

2021-05-12 22:40 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/GeneralMethods.cs
> +    public class GeneralMethods : IStarter
Этот класс вполне можно назвать `Starter`, более того, такое название будет более описательным.

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Database/OrderDatabase.cs
> +        }
you can use property default value
public List<Order> Orders { get; set; } = new List...

instead of constructor

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Database/OrderDatabase.cs
> +        public static void AddTOOrderDataBase(OrderDatabase database, IOrder order)
lowwer case

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Database/OrderDatabase.cs
> +            database.Orders.Add((Order)order);
do we really need this casting?

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Contracts/ICompany.cs
> +        List<Dish> Menu { get; set; }
consider use "Dishes" name

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Contracts/IOrder.cs
> +        List<Dish> Titles { get; set; }
consider use "Dishes" name

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Program.cs
> +            starter.Start(restraunt, customer);
restaurant

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Program.cs
> +            var restraunt = new Company();
recommendation is to use name same
i mean use Company or Restaurant as for type and for variable

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            int index;
better to combine

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Services/OrderServices.cs
> +
delete line

2021-06-01 19:33 UTC, yevhenbilushko commented on Delivery-service/Models/Services/Starter.cs
> +
delete one line

2021-06-01 20:51 UTC, kuleshovaann commented on Delivery-service/Models/Services/CustomerServices.cs
> +            int index;
what to combine?

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Models/Company.cs
> +        public string Name { get; set; }
properties and fields should before actor and methods

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Contracts/ICompany.cs
> +    public interface ICompany
you should use interfaces for services
not for entities

interface should contain behavior 
Name it is data not behavior

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Contracts/ICompany.cs
> +
please move "DataDelivery" to separete file
one type = one file

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Contracts/ICompany.cs
> +
wich project main ?
"Delivery-service" or "Models"
i think main should be as console app
another - class library project type

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Services/CompanyServices.cs
> +        public static void СompanyActions(ICompany company)
make sure it is english "C"

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            int index;
var index = int.Parse(Console.ReadLine());

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            UserUI.СustomerActionsUI();
UI should use logic of services
not oposite

2021-06-02 17:56 UTC, yevhenbilushko commented on Delivery-service/Models/Services/OrderServices.cs
> +                break;
do you need it
seems like loop act only once

2021-06-07 20:31 UTC, serhii-shkodenko requested changes

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Delivery-service/Program.cs
> -﻿using System;
Первое задание не нужно удалять. Его нужно сохранить. Или вынести в отдельный проект или вынести в отдельный файл.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICompanyServices.cs
> +        void CompanyActions(Company company) { }
Оставь в интерфейсе, пожалуйста, только контракты. Удали фигурные скобки.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICompanyServices.cs
> +        void AddDish(Company company, string name, double price, string composition, double weight, int calories) { }
Оставь в интерфейсе, пожалуйста, только контракты. Удали фигурные скобки.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICustomerServices.cs
> +        void СustomerActions(Company restraunt, Customer customer) { }
Оставь в интерфейсе, пожалуйста, только контракты. Удали фигурные скобки.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/ICustomerServices.cs
> +        void MakeOrder(Company restraunt, Customer customer) { }
Оставь в интерфейсе, пожалуйста, только контракты. Удали фигурные скобки.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Contracts/IOrderServices.cs
> +        void AddToOrder(Company company, Order order, int index) { }
Оставь в интерфейсе, пожалуйста, только контракты. Удали фигурные скобки.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Database/OrderDatabase.cs
> +    public class OrderDatabase
Хранилище тоже должно реализовывать интерфейс.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Database/OrderDatabase.cs
> +        public static void AddToOrderDataBase(OrderDatabase database, Order order)
Этот метод лучше удалить, он просто оборачивает метод `Add()` у списка. Пользуйся напрямую свойством `Orders`.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Program.cs
> +    class Program
Лучше добавить модификатор доступа.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Program.cs
> +        static void Main(string[] args)
Лучше добавить модификатор доступа.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CompanyServices.cs
> +            switch (int.Parse(Console.ReadLine()))
Лучше добавить дефолтный кейс. Для обработки случая, когда будет введено не то значение, которое ты ожидаешь.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CompanyServices.cs
> +            switch (int.Parse(Console.ReadLine()))
`int.Parse()` выдаст исключение, если парсинг будет неуданый. Попробуй `int.TryParse()`.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CompanyServices.cs
> +    public class CompanyServices : ICompanyServices
В конструктор этого класса должно приходить хранилище. Методы этого класса должны обращаться к нему.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +    public class CustomerServices : ICustomerServices
В конструктор этого класса должно приходить хранилище и его методы должны обращаться к нему.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            UserUI.СustomerActionsUI();
Этот комментрий не поправлен. Классы с бизнес логикой не должны содержать вызовов методов UI логики.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            UserUI.ShowFullPrice(order);
Классы с бизнес логикой не должны содержать вызовов методов UI логики.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/OrderServices.cs
> +                UserUI.GetVerificationOrder(company, index);
Классы с бизнес логикой не должны содержать вызовов методов UI логики.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices : IOrderServices
В конструктор этого класса должно приходить хранилище и его методы должны обращаться к нему.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/Starter.cs
> +            switch (int.Parse(Console.ReadLine()))
`int.Parse()` выдаст исключение, если парсинг будет неуданый. Попробуй `int.TryParse()`.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/Starter.cs
> +            switch (int.Parse(Console.ReadLine()))
Лучше добавить дефолтный кейс. Для обработки случая, когда будет введено не то значение, которое ты ожидаешь.

2021-06-07 20:31 UTC, serhii-shkodenko commented on Delivery-service/Models/UI/UserUI.cs
> +    public class UserUI
В конструктор этого класса должны приходить классы сервисов, к которым нужно обращаться за данными, обработанными в соответствии с бизнес логикой.

2021-06-08 16:51 UTC, kuleshovaann commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices : IOrderServices
Если честно, пока не понимаю, где здесь этот метод может обратиться к хранилищу.

2021-06-08 16:59 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices : IOrderServices
Ниже есть AddToOrder(), ты ему передаешь объекты, которыми он манипулирует. Вместо того чтобы пользоваться сайд эффектами ссылочных типов и менять объет по ссылке, переданной в метод (ее копии), слудет поступить так:
1. Передать в метод то, что нужно добавить.
2. Передать, например, Id заказа, куда надо добавить.
3.  Получить по Id заказ и изменить его в хранилище, воспользовавшись зависимостью, переданной в конструктор.

2021-06-09 23:15 UTC, serhii-shkodenko requested changes
Намного лучше. Это то что нужно. Чуть еще доработать и будет апрув.

2021-06-09 23:15 UTC, serhii-shkodenko commented on Delivery-service/Models/Models/Customer.cs
> +        public string[] PhoneNumbers { get; set; }
Лушче `IEnumerable<string>` вместо массивов. Или `List<T>`.

2021-06-09 23:15 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +            int index = int.Parse(Console.ReadLine());
Вот этот индекс должен быть передан из слоя UI. Передай его аргументом в этот метод. А этом метод вызови в слое UI.

2021-06-09 23:15 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +                index = int.Parse(Console.ReadLine());
Здесь такое же замечение, что и выше.

2021-06-11 10:26 UTC, kuleshovaann commented on Delivery-service/Models/Services/CustomerServices.cs
> +                index = int.Parse(Console.ReadLine());
Выше исправила,  но вот этот индекс находится в цикле для того, чтобы пользователь мог добавить несколько блюд в один заказ, а если я его вынесу за пределы метода, то тогда пользователь сможет добавить только одно блюдо в заказ.

2021-06-11 10:30 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/CustomerServices.cs
> +                index = int.Parse(Console.ReadLine());
Здесь дело не в том, что он в цикле, а в том, что здесь есть зависимость от слоя UI, который в нашем случае представлен консолью. То есть у тебя бизнес слой знает о слое UI, а может быть толькл наоборот. Поэтому этот цикл ты можешь вынести в слой UI.

2021-06-11 10:34 UTC, kuleshovaann commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices : IOrderServices
К сожалению, всё равно не поняла. Я тут просто добавляю блюдо в заказ, и с хранилищем это не связано.  А уже потом, как заказ полностью сформирован, ведь в одном заказе может быть несколько блюд, я добавляю заказ в хранилище.

2021-06-12 18:59 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-12 18:59 UTC, serhii-shkodenko commented on Delivery-service/Models/Services/OrderServices.cs
> +    public class OrderServices : IOrderServices
Здесь действительно нет никаких обращений к храналищу. Здесь просто создается объект. Поэтому можно было не делать ниаких классов для его формирования, а делать это в нужном тебе месте. Это на будущее, конкретно сейчас, ничего исправлять не нужно.

2021-06-12 20:04 UTC, merged